[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
evm_version = "paris"
optimizer_runs = 999999 # Etherscan does not support verifying contracts with more optimization runs.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
